### ISSUE TITLE
mods/UltimateLib/UltimateLib.Main.js not found

### ISSUE THREAD

**Issue by crazycodr** [abesco/gamedevtycoon-mods-ultimatelib#1]
If i knew what it was trying to find and load, i'd do a pull request to immediately fix it, but i have no idea what this file is supposed to be and do except maybe load everything in the project i guess!

Might want to check if you forgot to push a new file to your repo!

**Comment by RollAdvantage** [comment]
The master branch contains uncompressed/compiled scripts. Use the release branch. https://github.com/abesco/gamedevtycoon-mods-ultimatelib/tree/release

**Comment by crazycodr** [comment]
Oh, that's not clear in the README documentation and normally, you should branch off master to create a development branch if you want to a general DEV status then branch off dev for any feature you build. Master should always be your release because it's the default people start on.

Else i recommend you change your default branch in the settings of the project so that everyone new starts on release instead of master.

Later
